#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM_Hospital.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNS")]
	public partial class QLNSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBANGCHAMCONG(BANGCHAMCONG instance);
    partial void UpdateBANGCHAMCONG(BANGCHAMCONG instance);
    partial void DeleteBANGCHAMCONG(BANGCHAMCONG instance);
    partial void InsertTRINHDONGHIEPVU(TRINHDONGHIEPVU instance);
    partial void UpdateTRINHDONGHIEPVU(TRINHDONGHIEPVU instance);
    partial void DeleteTRINHDONGHIEPVU(TRINHDONGHIEPVU instance);
    partial void InsertCOTN(COTN instance);
    partial void UpdateCOTN(COTN instance);
    partial void DeleteCOTN(COTN instance);
    partial void InsertDONXIN(DONXIN instance);
    partial void UpdateDONXIN(DONXIN instance);
    partial void DeleteDONXIN(DONXIN instance);
    partial void InsertLICH(LICH instance);
    partial void UpdateLICH(LICH instance);
    partial void DeleteLICH(LICH instance);
    partial void InsertLUONG(LUONG instance);
    partial void UpdateLUONG(LUONG instance);
    partial void DeleteLUONG(LUONG instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertPHONGKHOA(PHONGKHOA instance);
    partial void UpdatePHONGKHOA(PHONGKHOA instance);
    partial void DeletePHONGKHOA(PHONGKHOA instance);
    partial void InsertQUATRINHCONGTAC(QUATRINHCONGTAC instance);
    partial void UpdateQUATRINHCONGTAC(QUATRINHCONGTAC instance);
    partial void DeleteQUATRINHCONGTAC(QUATRINHCONGTAC instance);
    partial void InsertQUYETDINH(QUYETDINH instance);
    partial void UpdateQUYETDINH(QUYETDINH instance);
    partial void DeleteQUYETDINH(QUYETDINH instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertTHANNHAN(THANNHAN instance);
    partial void UpdateTHANNHAN(THANNHAN instance);
    partial void DeleteTHANNHAN(THANNHAN instance);
    #endregion
		
		public QLNSDataContext() : 
				base(global::HRM_Hospital.Properties.Settings.Default.QLNSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BANGCHAMCONG> BANGCHAMCONGs
		{
			get
			{
				return this.GetTable<BANGCHAMCONG>();
			}
		}
		
		public System.Data.Linq.Table<TRINHDONGHIEPVU> TRINHDONGHIEPVUs
		{
			get
			{
				return this.GetTable<TRINHDONGHIEPVU>();
			}
		}
		
		public System.Data.Linq.Table<COTN> COTNs
		{
			get
			{
				return this.GetTable<COTN>();
			}
		}
		
		public System.Data.Linq.Table<DONXIN> DONXINs
		{
			get
			{
				return this.GetTable<DONXIN>();
			}
		}
		
		public System.Data.Linq.Table<LICH> LICHes
		{
			get
			{
				return this.GetTable<LICH>();
			}
		}
		
		public System.Data.Linq.Table<LUONG> LUONGs
		{
			get
			{
				return this.GetTable<LUONG>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHONGKHOA> PHONGKHOAs
		{
			get
			{
				return this.GetTable<PHONGKHOA>();
			}
		}
		
		public System.Data.Linq.Table<QUATRINHCONGTAC> QUATRINHCONGTACs
		{
			get
			{
				return this.GetTable<QUATRINHCONGTAC>();
			}
		}
		
		public System.Data.Linq.Table<QUYETDINH> QUYETDINHs
		{
			get
			{
				return this.GetTable<QUYETDINH>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<THANNHAN> THANNHANs
		{
			get
			{
				return this.GetTable<THANNHAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BANGCHAMCONG")]
	public partial class BANGCHAMCONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_BANGCC;
		
		private System.Nullable<int> _THANG;
		
		private string _MAPHG;
		
		private System.Nullable<int> _SONGAYCC;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
		private EntityRef<PHONGKHOA> _PHONGKHOA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_BANGCCChanging(string value);
    partial void OnMA_BANGCCChanged();
    partial void OnTHANGChanging(System.Nullable<int> value);
    partial void OnTHANGChanged();
    partial void OnMAPHGChanging(string value);
    partial void OnMAPHGChanged();
    partial void OnSONGAYCCChanging(System.Nullable<int> value);
    partial void OnSONGAYCCChanged();
    #endregion
		
		public BANGCHAMCONG()
		{
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			this._PHONGKHOA = default(EntityRef<PHONGKHOA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_BANGCC", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_BANGCC
		{
			get
			{
				return this._MA_BANGCC;
			}
			set
			{
				if ((this._MA_BANGCC != value))
				{
					this.OnMA_BANGCCChanging(value);
					this.SendPropertyChanging();
					this._MA_BANGCC = value;
					this.SendPropertyChanged("MA_BANGCC");
					this.OnMA_BANGCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANG", DbType="Int")]
		public System.Nullable<int> THANG
		{
			get
			{
				return this._THANG;
			}
			set
			{
				if ((this._THANG != value))
				{
					this.OnTHANGChanging(value);
					this.SendPropertyChanging();
					this._THANG = value;
					this.SendPropertyChanged("THANG");
					this.OnTHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHG", DbType="VarChar(4)")]
		public string MAPHG
		{
			get
			{
				return this._MAPHG;
			}
			set
			{
				if ((this._MAPHG != value))
				{
					if (this._PHONGKHOA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHGChanging(value);
					this.SendPropertyChanging();
					this._MAPHG = value;
					this.SendPropertyChanged("MAPHG");
					this.OnMAPHGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONGAYCC", DbType="Int")]
		public System.Nullable<int> SONGAYCC
		{
			get
			{
				return this._SONGAYCC;
			}
			set
			{
				if ((this._SONGAYCC != value))
				{
					this.OnSONGAYCCChanging(value);
					this.SendPropertyChanging();
					this._SONGAYCC = value;
					this.SendPropertyChanged("SONGAYCC");
					this.OnSONGAYCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGCHAMCONG_NHANVIEN", Storage="_NHANVIENs", ThisKey="MA_BANGCC", OtherKey="MA_BANGCC")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGKHOA_BANGCHAMCONG", Storage="_PHONGKHOA", ThisKey="MAPHG", OtherKey="MAPHG", IsForeignKey=true)]
		public PHONGKHOA PHONGKHOA
		{
			get
			{
				return this._PHONGKHOA.Entity;
			}
			set
			{
				PHONGKHOA previousValue = this._PHONGKHOA.Entity;
				if (((previousValue != value) 
							|| (this._PHONGKHOA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONGKHOA.Entity = null;
						previousValue.BANGCHAMCONGs.Remove(this);
					}
					this._PHONGKHOA.Entity = value;
					if ((value != null))
					{
						value.BANGCHAMCONGs.Add(this);
						this._MAPHG = value.MAPHG;
					}
					else
					{
						this._MAPHG = default(string);
					}
					this.SendPropertyChanged("PHONGKHOA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.BANGCHAMCONG = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.BANGCHAMCONG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRINHDONGHIEPVU")]
	public partial class TRINHDONGHIEPVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATDNV;
		
		private string _TENTRUONG;
		
		private string _TENLOPHOCNV;
		
		private System.Nullable<System.DateTime> _THOIGIANHOCNV;
		
		private string _HINHTHUCHOCNV;
		
		private string _CHUNGNHAN;
		
		private string _MANV;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATDNVChanging(string value);
    partial void OnMATDNVChanged();
    partial void OnTENTRUONGChanging(string value);
    partial void OnTENTRUONGChanged();
    partial void OnTENLOPHOCNVChanging(string value);
    partial void OnTENLOPHOCNVChanged();
    partial void OnTHOIGIANHOCNVChanging(System.Nullable<System.DateTime> value);
    partial void OnTHOIGIANHOCNVChanged();
    partial void OnHINHTHUCHOCNVChanging(string value);
    partial void OnHINHTHUCHOCNVChanged();
    partial void OnCHUNGNHANChanging(string value);
    partial void OnCHUNGNHANChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    #endregion
		
		public TRINHDONGHIEPVU()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATDNV", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATDNV
		{
			get
			{
				return this._MATDNV;
			}
			set
			{
				if ((this._MATDNV != value))
				{
					this.OnMATDNVChanging(value);
					this.SendPropertyChanging();
					this._MATDNV = value;
					this.SendPropertyChanged("MATDNV");
					this.OnMATDNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTRUONG", DbType="Char(50)")]
		public string TENTRUONG
		{
			get
			{
				return this._TENTRUONG;
			}
			set
			{
				if ((this._TENTRUONG != value))
				{
					this.OnTENTRUONGChanging(value);
					this.SendPropertyChanging();
					this._TENTRUONG = value;
					this.SendPropertyChanged("TENTRUONG");
					this.OnTENTRUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOPHOCNV", DbType="Char(50)")]
		public string TENLOPHOCNV
		{
			get
			{
				return this._TENLOPHOCNV;
			}
			set
			{
				if ((this._TENLOPHOCNV != value))
				{
					this.OnTENLOPHOCNVChanging(value);
					this.SendPropertyChanging();
					this._TENLOPHOCNV = value;
					this.SendPropertyChanged("TENLOPHOCNV");
					this.OnTENLOPHOCNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIANHOCNV", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> THOIGIANHOCNV
		{
			get
			{
				return this._THOIGIANHOCNV;
			}
			set
			{
				if ((this._THOIGIANHOCNV != value))
				{
					this.OnTHOIGIANHOCNVChanging(value);
					this.SendPropertyChanging();
					this._THOIGIANHOCNV = value;
					this.SendPropertyChanged("THOIGIANHOCNV");
					this.OnTHOIGIANHOCNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHTHUCHOCNV", DbType="Char(30)")]
		public string HINHTHUCHOCNV
		{
			get
			{
				return this._HINHTHUCHOCNV;
			}
			set
			{
				if ((this._HINHTHUCHOCNV != value))
				{
					this.OnHINHTHUCHOCNVChanging(value);
					this.SendPropertyChanging();
					this._HINHTHUCHOCNV = value;
					this.SendPropertyChanged("HINHTHUCHOCNV");
					this.OnHINHTHUCHOCNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUNGNHAN", DbType="Char(50)")]
		public string CHUNGNHAN
		{
			get
			{
				return this._CHUNGNHAN;
			}
			set
			{
				if ((this._CHUNGNHAN != value))
				{
					this.OnCHUNGNHANChanging(value);
					this.SendPropertyChanging();
					this._CHUNGNHAN = value;
					this.SendPropertyChanged("CHUNGNHAN");
					this.OnCHUNGNHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(4)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TRINHDONGHIEPVU", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.TRINHDONGHIEPVUs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.TRINHDONGHIEPVUs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.COTN")]
	public partial class COTN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _MATN;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<THANNHAN> _THANNHAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMATNChanging(string value);
    partial void OnMATNChanged();
    #endregion
		
		public COTN()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._THANNHAN = default(EntityRef<THANNHAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATN", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATN
		{
			get
			{
				return this._MATN;
			}
			set
			{
				if ((this._MATN != value))
				{
					if (this._THANNHAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMATNChanging(value);
					this.SendPropertyChanging();
					this._MATN = value;
					this.SendPropertyChanged("MATN");
					this.OnMATNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_COTN", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.COTNs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.COTNs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANNHAN_COTN", Storage="_THANNHAN", ThisKey="MATN", OtherKey="MATN", IsForeignKey=true)]
		public THANNHAN THANNHAN
		{
			get
			{
				return this._THANNHAN.Entity;
			}
			set
			{
				THANNHAN previousValue = this._THANNHAN.Entity;
				if (((previousValue != value) 
							|| (this._THANNHAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THANNHAN.Entity = null;
						previousValue.COTNs.Remove(this);
					}
					this._THANNHAN.Entity = value;
					if ((value != null))
					{
						value.COTNs.Add(this);
						this._MATN = value.MATN;
					}
					else
					{
						this._MATN = default(string);
					}
					this.SendPropertyChanged("THANNHAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DONXIN")]
	public partial class DONXIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MADONXIN;
		
		private string _MANV;
		
		private System.Nullable<int> _SONGAYNGHI;
		
		private string _LYDO;
		
		private System.Nullable<System.DateTime> _TUNGAY;
		
		private System.Nullable<System.DateTime> _DENNGAY;
		
		private System.Nullable<System.DateTime> _NGAYLAPDON;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMADONXINChanging(string value);
    partial void OnMADONXINChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnSONGAYNGHIChanging(System.Nullable<int> value);
    partial void OnSONGAYNGHIChanged();
    partial void OnLYDOChanging(string value);
    partial void OnLYDOChanged();
    partial void OnTUNGAYChanging(System.Nullable<System.DateTime> value);
    partial void OnTUNGAYChanged();
    partial void OnDENNGAYChanging(System.Nullable<System.DateTime> value);
    partial void OnDENNGAYChanged();
    partial void OnNGAYLAPDONChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYLAPDONChanged();
    #endregion
		
		public DONXIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MADONXIN", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MADONXIN
		{
			get
			{
				return this._MADONXIN;
			}
			set
			{
				if ((this._MADONXIN != value))
				{
					this.OnMADONXINChanging(value);
					this.SendPropertyChanging();
					this._MADONXIN = value;
					this.SendPropertyChanged("MADONXIN");
					this.OnMADONXINChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(4)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SONGAYNGHI", DbType="Int")]
		public System.Nullable<int> SONGAYNGHI
		{
			get
			{
				return this._SONGAYNGHI;
			}
			set
			{
				if ((this._SONGAYNGHI != value))
				{
					this.OnSONGAYNGHIChanging(value);
					this.SendPropertyChanging();
					this._SONGAYNGHI = value;
					this.SendPropertyChanged("SONGAYNGHI");
					this.OnSONGAYNGHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LYDO", DbType="NVarChar(100)")]
		public string LYDO
		{
			get
			{
				return this._LYDO;
			}
			set
			{
				if ((this._LYDO != value))
				{
					this.OnLYDOChanging(value);
					this.SendPropertyChanging();
					this._LYDO = value;
					this.SendPropertyChanged("LYDO");
					this.OnLYDOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUNGAY", DbType="Date")]
		public System.Nullable<System.DateTime> TUNGAY
		{
			get
			{
				return this._TUNGAY;
			}
			set
			{
				if ((this._TUNGAY != value))
				{
					this.OnTUNGAYChanging(value);
					this.SendPropertyChanging();
					this._TUNGAY = value;
					this.SendPropertyChanged("TUNGAY");
					this.OnTUNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DENNGAY", DbType="Date")]
		public System.Nullable<System.DateTime> DENNGAY
		{
			get
			{
				return this._DENNGAY;
			}
			set
			{
				if ((this._DENNGAY != value))
				{
					this.OnDENNGAYChanging(value);
					this.SendPropertyChanging();
					this._DENNGAY = value;
					this.SendPropertyChanged("DENNGAY");
					this.OnDENNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYLAPDON", DbType="Date")]
		public System.Nullable<System.DateTime> NGAYLAPDON
		{
			get
			{
				return this._NGAYLAPDON;
			}
			set
			{
				if ((this._NGAYLAPDON != value))
				{
					this.OnNGAYLAPDONChanging(value);
					this.SendPropertyChanging();
					this._NGAYLAPDON = value;
					this.SendPropertyChanged("NGAYLAPDON");
					this.OnNGAYLAPDONChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LICH")]
	public partial class LICH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALICH;
		
		private string _MANV;
		
		private string _MAPHG;
		
		private string _TENCV;
		
		private string _LOAICV;
		
		private System.Nullable<System.DateTime> _NGAY;
		
		private System.Nullable<System.DateTime> _THOIGIAN;
		
		private string _DIADIEM;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
		private EntityRef<PHONGKHOA> _PHONGKHOA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALICHChanging(string value);
    partial void OnMALICHChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMAPHGChanging(string value);
    partial void OnMAPHGChanged();
    partial void OnTENCVChanging(string value);
    partial void OnTENCVChanged();
    partial void OnLOAICVChanging(string value);
    partial void OnLOAICVChanged();
    partial void OnNGAYChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYChanged();
    partial void OnTHOIGIANChanging(System.Nullable<System.DateTime> value);
    partial void OnTHOIGIANChanged();
    partial void OnDIADIEMChanging(string value);
    partial void OnDIADIEMChanged();
    #endregion
		
		public LICH()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			this._PHONGKHOA = default(EntityRef<PHONGKHOA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALICH", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALICH
		{
			get
			{
				return this._MALICH;
			}
			set
			{
				if ((this._MALICH != value))
				{
					this.OnMALICHChanging(value);
					this.SendPropertyChanging();
					this._MALICH = value;
					this.SendPropertyChanged("MALICH");
					this.OnMALICHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(4)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHG", DbType="VarChar(4)")]
		public string MAPHG
		{
			get
			{
				return this._MAPHG;
			}
			set
			{
				if ((this._MAPHG != value))
				{
					if (this._PHONGKHOA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHGChanging(value);
					this.SendPropertyChanging();
					this._MAPHG = value;
					this.SendPropertyChanged("MAPHG");
					this.OnMAPHGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENCV", DbType="Char(50)")]
		public string TENCV
		{
			get
			{
				return this._TENCV;
			}
			set
			{
				if ((this._TENCV != value))
				{
					this.OnTENCVChanging(value);
					this.SendPropertyChanging();
					this._TENCV = value;
					this.SendPropertyChanged("TENCV");
					this.OnTENCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAICV", DbType="Char(20)")]
		public string LOAICV
		{
			get
			{
				return this._LOAICV;
			}
			set
			{
				if ((this._LOAICV != value))
				{
					this.OnLOAICVChanging(value);
					this.SendPropertyChanging();
					this._LOAICV = value;
					this.SendPropertyChanged("LOAICV");
					this.OnLOAICVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NGAY
		{
			get
			{
				return this._NGAY;
			}
			set
			{
				if ((this._NGAY != value))
				{
					this.OnNGAYChanging(value);
					this.SendPropertyChanging();
					this._NGAY = value;
					this.SendPropertyChanged("NGAY");
					this.OnNGAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIAN", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> THOIGIAN
		{
			get
			{
				return this._THOIGIAN;
			}
			set
			{
				if ((this._THOIGIAN != value))
				{
					this.OnTHOIGIANChanging(value);
					this.SendPropertyChanging();
					this._THOIGIAN = value;
					this.SendPropertyChanged("THOIGIAN");
					this.OnTHOIGIANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIADIEM", DbType="Char(50)")]
		public string DIADIEM
		{
			get
			{
				return this._DIADIEM;
			}
			set
			{
				if ((this._DIADIEM != value))
				{
					this.OnDIADIEMChanging(value);
					this.SendPropertyChanging();
					this._DIADIEM = value;
					this.SendPropertyChanged("DIADIEM");
					this.OnDIADIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_LICH", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.LICHes.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.LICHes.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGKHOA_LICH", Storage="_PHONGKHOA", ThisKey="MAPHG", OtherKey="MAPHG", IsForeignKey=true)]
		public PHONGKHOA PHONGKHOA
		{
			get
			{
				return this._PHONGKHOA.Entity;
			}
			set
			{
				PHONGKHOA previousValue = this._PHONGKHOA.Entity;
				if (((previousValue != value) 
							|| (this._PHONGKHOA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONGKHOA.Entity = null;
						previousValue.LICHes.Remove(this);
					}
					this._PHONGKHOA.Entity = value;
					if ((value != null))
					{
						value.LICHes.Add(this);
						this._MAPHG = value.MAPHG;
					}
					else
					{
						this._MAPHG = default(string);
					}
					this.SendPropertyChanged("PHONGKHOA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LUONG")]
	public partial class LUONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _MALUONG;
		
		private System.Nullable<decimal> _LUONG1;
		
		private System.Nullable<decimal> _PHUCAP;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMALUONGChanging(string value);
    partial void OnMALUONGChanged();
    partial void OnLUONG1Changing(System.Nullable<decimal> value);
    partial void OnLUONG1Changed();
    partial void OnPHUCAPChanging(System.Nullable<decimal> value);
    partial void OnPHUCAPChanged();
    #endregion
		
		public LUONG()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(4)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALUONG", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALUONG
		{
			get
			{
				return this._MALUONG;
			}
			set
			{
				if ((this._MALUONG != value))
				{
					this.OnMALUONGChanging(value);
					this.SendPropertyChanging();
					this._MALUONG = value;
					this.SendPropertyChanged("MALUONG");
					this.OnMALUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="LUONG", Storage="_LUONG1", DbType="Money")]
		public System.Nullable<decimal> LUONG1
		{
			get
			{
				return this._LUONG1;
			}
			set
			{
				if ((this._LUONG1 != value))
				{
					this.OnLUONG1Changing(value);
					this.SendPropertyChanging();
					this._LUONG1 = value;
					this.SendPropertyChanged("LUONG1");
					this.OnLUONG1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHUCAP", DbType="Money")]
		public System.Nullable<decimal> PHUCAP
		{
			get
			{
				return this._PHUCAP;
			}
			set
			{
				if ((this._PHUCAP != value))
				{
					this.OnPHUCAPChanging(value);
					this.SendPropertyChanging();
					this._PHUCAP = value;
					this.SendPropertyChanged("PHUCAP");
					this.OnPHUCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_LUONG", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.LUONGs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.LUONGs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MANV;
		
		private string _MA_BANGCC;
		
		private string _HOTENNV;
		
		private System.Nullable<bool> _PHAI;
		
		private System.Nullable<System.DateTime> _NGAYSINH;
		
		private string _CMND;
		
		private string _QUEQUAN;
		
		private string _NOIOHIENTAI;
		
		private string _DANTOC;
		
		private string _TONGIAO;
		
		private System.Nullable<System.DateTime> _NGAYVAODANG;
		
		private string _DANHHIEU;
		
		private string _NGACH;
		
		private string _BAC;
		
		private string _LOAITHUONGBINH;
		
		private System.Nullable<bool> _GIADINHLIETSI;
		
		private string _LOAINV;
		
		private EntitySet<TRINHDONGHIEPVU> _TRINHDONGHIEPVUs;
		
		private EntitySet<COTN> _COTNs;
		
		private EntitySet<LICH> _LICHes;
		
		private EntitySet<LUONG> _LUONGs;
		
		private EntitySet<QUATRINHCONGTAC> _QUATRINHCONGTACs;
		
		private EntitySet<QUYETDINH> _QUYETDINHs;
		
		private EntitySet<TAIKHOAN> _TAIKHOANs;
		
		private EntityRef<BANGCHAMCONG> _BANGCHAMCONG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMA_BANGCCChanging(string value);
    partial void OnMA_BANGCCChanged();
    partial void OnHOTENNVChanging(string value);
    partial void OnHOTENNVChanged();
    partial void OnPHAIChanging(System.Nullable<bool> value);
    partial void OnPHAIChanged();
    partial void OnNGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYSINHChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnQUEQUANChanging(string value);
    partial void OnQUEQUANChanged();
    partial void OnNOIOHIENTAIChanging(string value);
    partial void OnNOIOHIENTAIChanged();
    partial void OnDANTOCChanging(string value);
    partial void OnDANTOCChanged();
    partial void OnTONGIAOChanging(string value);
    partial void OnTONGIAOChanged();
    partial void OnNGAYVAODANGChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYVAODANGChanged();
    partial void OnDANHHIEUChanging(string value);
    partial void OnDANHHIEUChanged();
    partial void OnNGACHChanging(string value);
    partial void OnNGACHChanged();
    partial void OnBACChanging(string value);
    partial void OnBACChanged();
    partial void OnLOAITHUONGBINHChanging(string value);
    partial void OnLOAITHUONGBINHChanged();
    partial void OnGIADINHLIETSIChanging(System.Nullable<bool> value);
    partial void OnGIADINHLIETSIChanged();
    partial void OnLOAINVChanging(string value);
    partial void OnLOAINVChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._TRINHDONGHIEPVUs = new EntitySet<TRINHDONGHIEPVU>(new Action<TRINHDONGHIEPVU>(this.attach_TRINHDONGHIEPVUs), new Action<TRINHDONGHIEPVU>(this.detach_TRINHDONGHIEPVUs));
			this._COTNs = new EntitySet<COTN>(new Action<COTN>(this.attach_COTNs), new Action<COTN>(this.detach_COTNs));
			this._LICHes = new EntitySet<LICH>(new Action<LICH>(this.attach_LICHes), new Action<LICH>(this.detach_LICHes));
			this._LUONGs = new EntitySet<LUONG>(new Action<LUONG>(this.attach_LUONGs), new Action<LUONG>(this.detach_LUONGs));
			this._QUATRINHCONGTACs = new EntitySet<QUATRINHCONGTAC>(new Action<QUATRINHCONGTAC>(this.attach_QUATRINHCONGTACs), new Action<QUATRINHCONGTAC>(this.detach_QUATRINHCONGTACs));
			this._QUYETDINHs = new EntitySet<QUYETDINH>(new Action<QUYETDINH>(this.attach_QUYETDINHs), new Action<QUYETDINH>(this.detach_QUYETDINHs));
			this._TAIKHOANs = new EntitySet<TAIKHOAN>(new Action<TAIKHOAN>(this.attach_TAIKHOANs), new Action<TAIKHOAN>(this.detach_TAIKHOANs));
			this._BANGCHAMCONG = default(EntityRef<BANGCHAMCONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_BANGCC", DbType="VarChar(4)")]
		public string MA_BANGCC
		{
			get
			{
				return this._MA_BANGCC;
			}
			set
			{
				if ((this._MA_BANGCC != value))
				{
					if (this._BANGCHAMCONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_BANGCCChanging(value);
					this.SendPropertyChanging();
					this._MA_BANGCC = value;
					this.SendPropertyChanged("MA_BANGCC");
					this.OnMA_BANGCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENNV", DbType="Char(50)")]
		public string HOTENNV
		{
			get
			{
				return this._HOTENNV;
			}
			set
			{
				if ((this._HOTENNV != value))
				{
					this.OnHOTENNVChanging(value);
					this.SendPropertyChanging();
					this._HOTENNV = value;
					this.SendPropertyChanged("HOTENNV");
					this.OnHOTENNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PHAI", DbType="Bit")]
		public System.Nullable<bool> PHAI
		{
			get
			{
				return this._PHAI;
			}
			set
			{
				if ((this._PHAI != value))
				{
					this.OnPHAIChanging(value);
					this.SendPropertyChanging();
					this._PHAI = value;
					this.SendPropertyChanged("PHAI");
					this.OnPHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYSINH", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NGAYSINH
		{
			get
			{
				return this._NGAYSINH;
			}
			set
			{
				if ((this._NGAYSINH != value))
				{
					this.OnNGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._NGAYSINH = value;
					this.SendPropertyChanged("NGAYSINH");
					this.OnNGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Char(20)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUEQUAN", DbType="Char(50)")]
		public string QUEQUAN
		{
			get
			{
				return this._QUEQUAN;
			}
			set
			{
				if ((this._QUEQUAN != value))
				{
					this.OnQUEQUANChanging(value);
					this.SendPropertyChanging();
					this._QUEQUAN = value;
					this.SendPropertyChanged("QUEQUAN");
					this.OnQUEQUANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIOHIENTAI", DbType="Char(100)")]
		public string NOIOHIENTAI
		{
			get
			{
				return this._NOIOHIENTAI;
			}
			set
			{
				if ((this._NOIOHIENTAI != value))
				{
					this.OnNOIOHIENTAIChanging(value);
					this.SendPropertyChanging();
					this._NOIOHIENTAI = value;
					this.SendPropertyChanged("NOIOHIENTAI");
					this.OnNOIOHIENTAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DANTOC", DbType="Char(20)")]
		public string DANTOC
		{
			get
			{
				return this._DANTOC;
			}
			set
			{
				if ((this._DANTOC != value))
				{
					this.OnDANTOCChanging(value);
					this.SendPropertyChanging();
					this._DANTOC = value;
					this.SendPropertyChanged("DANTOC");
					this.OnDANTOCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONGIAO", DbType="Char(20)")]
		public string TONGIAO
		{
			get
			{
				return this._TONGIAO;
			}
			set
			{
				if ((this._TONGIAO != value))
				{
					this.OnTONGIAOChanging(value);
					this.SendPropertyChanging();
					this._TONGIAO = value;
					this.SendPropertyChanged("TONGIAO");
					this.OnTONGIAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYVAODANG", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NGAYVAODANG
		{
			get
			{
				return this._NGAYVAODANG;
			}
			set
			{
				if ((this._NGAYVAODANG != value))
				{
					this.OnNGAYVAODANGChanging(value);
					this.SendPropertyChanging();
					this._NGAYVAODANG = value;
					this.SendPropertyChanged("NGAYVAODANG");
					this.OnNGAYVAODANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DANHHIEU", DbType="Char(50)")]
		public string DANHHIEU
		{
			get
			{
				return this._DANHHIEU;
			}
			set
			{
				if ((this._DANHHIEU != value))
				{
					this.OnDANHHIEUChanging(value);
					this.SendPropertyChanging();
					this._DANHHIEU = value;
					this.SendPropertyChanged("DANHHIEU");
					this.OnDANHHIEUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGACH", DbType="Char(40)")]
		public string NGACH
		{
			get
			{
				return this._NGACH;
			}
			set
			{
				if ((this._NGACH != value))
				{
					this.OnNGACHChanging(value);
					this.SendPropertyChanging();
					this._NGACH = value;
					this.SendPropertyChanged("NGACH");
					this.OnNGACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BAC", DbType="Char(30)")]
		public string BAC
		{
			get
			{
				return this._BAC;
			}
			set
			{
				if ((this._BAC != value))
				{
					this.OnBACChanging(value);
					this.SendPropertyChanging();
					this._BAC = value;
					this.SendPropertyChanged("BAC");
					this.OnBACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAITHUONGBINH", DbType="Char(20)")]
		public string LOAITHUONGBINH
		{
			get
			{
				return this._LOAITHUONGBINH;
			}
			set
			{
				if ((this._LOAITHUONGBINH != value))
				{
					this.OnLOAITHUONGBINHChanging(value);
					this.SendPropertyChanging();
					this._LOAITHUONGBINH = value;
					this.SendPropertyChanged("LOAITHUONGBINH");
					this.OnLOAITHUONGBINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIADINHLIETSI", DbType="Bit")]
		public System.Nullable<bool> GIADINHLIETSI
		{
			get
			{
				return this._GIADINHLIETSI;
			}
			set
			{
				if ((this._GIADINHLIETSI != value))
				{
					this.OnGIADINHLIETSIChanging(value);
					this.SendPropertyChanging();
					this._GIADINHLIETSI = value;
					this.SendPropertyChanged("GIADINHLIETSI");
					this.OnGIADINHLIETSIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAINV", DbType="Char(20)")]
		public string LOAINV
		{
			get
			{
				return this._LOAINV;
			}
			set
			{
				if ((this._LOAINV != value))
				{
					this.OnLOAINVChanging(value);
					this.SendPropertyChanging();
					this._LOAINV = value;
					this.SendPropertyChanged("LOAINV");
					this.OnLOAINVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TRINHDONGHIEPVU", Storage="_TRINHDONGHIEPVUs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<TRINHDONGHIEPVU> TRINHDONGHIEPVUs
		{
			get
			{
				return this._TRINHDONGHIEPVUs;
			}
			set
			{
				this._TRINHDONGHIEPVUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_COTN", Storage="_COTNs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<COTN> COTNs
		{
			get
			{
				return this._COTNs;
			}
			set
			{
				this._COTNs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_LICH", Storage="_LICHes", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<LICH> LICHes
		{
			get
			{
				return this._LICHes;
			}
			set
			{
				this._LICHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_LUONG", Storage="_LUONGs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<LUONG> LUONGs
		{
			get
			{
				return this._LUONGs;
			}
			set
			{
				this._LUONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_QUATRINHCONGTAC", Storage="_QUATRINHCONGTACs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<QUATRINHCONGTAC> QUATRINHCONGTACs
		{
			get
			{
				return this._QUATRINHCONGTACs;
			}
			set
			{
				this._QUATRINHCONGTACs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_QUYETDINH", Storage="_QUYETDINHs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<QUYETDINH> QUYETDINHs
		{
			get
			{
				return this._QUYETDINHs;
			}
			set
			{
				this._QUYETDINHs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TAIKHOAN", Storage="_TAIKHOANs", ThisKey="MANV", OtherKey="MANV")]
		public EntitySet<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this._TAIKHOANs;
			}
			set
			{
				this._TAIKHOANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BANGCHAMCONG_NHANVIEN", Storage="_BANGCHAMCONG", ThisKey="MA_BANGCC", OtherKey="MA_BANGCC", IsForeignKey=true)]
		public BANGCHAMCONG BANGCHAMCONG
		{
			get
			{
				return this._BANGCHAMCONG.Entity;
			}
			set
			{
				BANGCHAMCONG previousValue = this._BANGCHAMCONG.Entity;
				if (((previousValue != value) 
							|| (this._BANGCHAMCONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BANGCHAMCONG.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._BANGCHAMCONG.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._MA_BANGCC = value.MA_BANGCC;
					}
					else
					{
						this._MA_BANGCC = default(string);
					}
					this.SendPropertyChanged("BANGCHAMCONG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRINHDONGHIEPVUs(TRINHDONGHIEPVU entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_TRINHDONGHIEPVUs(TRINHDONGHIEPVU entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_COTNs(COTN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_COTNs(COTN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_LICHes(LICH entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_LICHes(LICH entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_LUONGs(LUONG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_LUONGs(LUONG entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_QUATRINHCONGTACs(QUATRINHCONGTAC entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_QUATRINHCONGTACs(QUATRINHCONGTAC entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_QUYETDINHs(QUYETDINH entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_QUYETDINHs(QUYETDINH entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_TAIKHOANs(TAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_TAIKHOANs(TAIKHOAN entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONGKHOA")]
	public partial class PHONGKHOA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAPHG;
		
		private string _TENPHG;
		
		private string _KHOI;
		
		private EntitySet<BANGCHAMCONG> _BANGCHAMCONGs;
		
		private EntitySet<LICH> _LICHes;
		
		private EntitySet<QUATRINHCONGTAC> _QUATRINHCONGTACs;
		
		private EntitySet<QUYETDINH> _QUYETDINHs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAPHGChanging(string value);
    partial void OnMAPHGChanged();
    partial void OnTENPHGChanging(string value);
    partial void OnTENPHGChanged();
    partial void OnKHOIChanging(string value);
    partial void OnKHOIChanged();
    #endregion
		
		public PHONGKHOA()
		{
			this._BANGCHAMCONGs = new EntitySet<BANGCHAMCONG>(new Action<BANGCHAMCONG>(this.attach_BANGCHAMCONGs), new Action<BANGCHAMCONG>(this.detach_BANGCHAMCONGs));
			this._LICHes = new EntitySet<LICH>(new Action<LICH>(this.attach_LICHes), new Action<LICH>(this.detach_LICHes));
			this._QUATRINHCONGTACs = new EntitySet<QUATRINHCONGTAC>(new Action<QUATRINHCONGTAC>(this.attach_QUATRINHCONGTACs), new Action<QUATRINHCONGTAC>(this.detach_QUATRINHCONGTACs));
			this._QUYETDINHs = new EntitySet<QUYETDINH>(new Action<QUYETDINH>(this.attach_QUYETDINHs), new Action<QUYETDINH>(this.detach_QUYETDINHs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHG", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAPHG
		{
			get
			{
				return this._MAPHG;
			}
			set
			{
				if ((this._MAPHG != value))
				{
					this.OnMAPHGChanging(value);
					this.SendPropertyChanging();
					this._MAPHG = value;
					this.SendPropertyChanged("MAPHG");
					this.OnMAPHGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENPHG", DbType="Char(50)")]
		public string TENPHG
		{
			get
			{
				return this._TENPHG;
			}
			set
			{
				if ((this._TENPHG != value))
				{
					this.OnTENPHGChanging(value);
					this.SendPropertyChanging();
					this._TENPHG = value;
					this.SendPropertyChanged("TENPHG");
					this.OnTENPHGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHOI", DbType="Char(50)")]
		public string KHOI
		{
			get
			{
				return this._KHOI;
			}
			set
			{
				if ((this._KHOI != value))
				{
					this.OnKHOIChanging(value);
					this.SendPropertyChanging();
					this._KHOI = value;
					this.SendPropertyChanged("KHOI");
					this.OnKHOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGKHOA_BANGCHAMCONG", Storage="_BANGCHAMCONGs", ThisKey="MAPHG", OtherKey="MAPHG")]
		public EntitySet<BANGCHAMCONG> BANGCHAMCONGs
		{
			get
			{
				return this._BANGCHAMCONGs;
			}
			set
			{
				this._BANGCHAMCONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGKHOA_LICH", Storage="_LICHes", ThisKey="MAPHG", OtherKey="MAPHG")]
		public EntitySet<LICH> LICHes
		{
			get
			{
				return this._LICHes;
			}
			set
			{
				this._LICHes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGKHOA_QUATRINHCONGTAC", Storage="_QUATRINHCONGTACs", ThisKey="MAPHG", OtherKey="MAPHG")]
		public EntitySet<QUATRINHCONGTAC> QUATRINHCONGTACs
		{
			get
			{
				return this._QUATRINHCONGTACs;
			}
			set
			{
				this._QUATRINHCONGTACs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGKHOA_QUYETDINH", Storage="_QUYETDINHs", ThisKey="MAPHG", OtherKey="MAPHG")]
		public EntitySet<QUYETDINH> QUYETDINHs
		{
			get
			{
				return this._QUYETDINHs;
			}
			set
			{
				this._QUYETDINHs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BANGCHAMCONGs(BANGCHAMCONG entity)
		{
			this.SendPropertyChanging();
			entity.PHONGKHOA = this;
		}
		
		private void detach_BANGCHAMCONGs(BANGCHAMCONG entity)
		{
			this.SendPropertyChanging();
			entity.PHONGKHOA = null;
		}
		
		private void attach_LICHes(LICH entity)
		{
			this.SendPropertyChanging();
			entity.PHONGKHOA = this;
		}
		
		private void detach_LICHes(LICH entity)
		{
			this.SendPropertyChanging();
			entity.PHONGKHOA = null;
		}
		
		private void attach_QUATRINHCONGTACs(QUATRINHCONGTAC entity)
		{
			this.SendPropertyChanging();
			entity.PHONGKHOA = this;
		}
		
		private void detach_QUATRINHCONGTACs(QUATRINHCONGTAC entity)
		{
			this.SendPropertyChanging();
			entity.PHONGKHOA = null;
		}
		
		private void attach_QUYETDINHs(QUYETDINH entity)
		{
			this.SendPropertyChanging();
			entity.PHONGKHOA = this;
		}
		
		private void detach_QUYETDINHs(QUYETDINH entity)
		{
			this.SendPropertyChanging();
			entity.PHONGKHOA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUATRINHCONGTAC")]
	public partial class QUATRINHCONGTAC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAQTCT;
		
		private string _MANV;
		
		private string _MAPHG;
		
		private System.Nullable<System.DateTime> _TUTHANG_NAM;
		
		private System.Nullable<System.DateTime> _DENTHANG_NAM;
		
		private string _CHUCDANH;
		
		private string _CHUCVU;
		
		private EntityRef<PHONGKHOA> _PHONGKHOA;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAQTCTChanging(string value);
    partial void OnMAQTCTChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMAPHGChanging(string value);
    partial void OnMAPHGChanged();
    partial void OnTUTHANG_NAMChanging(System.Nullable<System.DateTime> value);
    partial void OnTUTHANG_NAMChanged();
    partial void OnDENTHANG_NAMChanging(System.Nullable<System.DateTime> value);
    partial void OnDENTHANG_NAMChanged();
    partial void OnCHUCDANHChanging(string value);
    partial void OnCHUCDANHChanged();
    partial void OnCHUCVUChanging(string value);
    partial void OnCHUCVUChanged();
    #endregion
		
		public QUATRINHCONGTAC()
		{
			this._PHONGKHOA = default(EntityRef<PHONGKHOA>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAQTCT", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAQTCT
		{
			get
			{
				return this._MAQTCT;
			}
			set
			{
				if ((this._MAQTCT != value))
				{
					this.OnMAQTCTChanging(value);
					this.SendPropertyChanging();
					this._MAQTCT = value;
					this.SendPropertyChanged("MAQTCT");
					this.OnMAQTCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(4)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHG", DbType="VarChar(4)")]
		public string MAPHG
		{
			get
			{
				return this._MAPHG;
			}
			set
			{
				if ((this._MAPHG != value))
				{
					if (this._PHONGKHOA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHGChanging(value);
					this.SendPropertyChanging();
					this._MAPHG = value;
					this.SendPropertyChanged("MAPHG");
					this.OnMAPHGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUTHANG_NAM", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> TUTHANG_NAM
		{
			get
			{
				return this._TUTHANG_NAM;
			}
			set
			{
				if ((this._TUTHANG_NAM != value))
				{
					this.OnTUTHANG_NAMChanging(value);
					this.SendPropertyChanging();
					this._TUTHANG_NAM = value;
					this.SendPropertyChanged("TUTHANG_NAM");
					this.OnTUTHANG_NAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DENTHANG_NAM", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DENTHANG_NAM
		{
			get
			{
				return this._DENTHANG_NAM;
			}
			set
			{
				if ((this._DENTHANG_NAM != value))
				{
					this.OnDENTHANG_NAMChanging(value);
					this.SendPropertyChanging();
					this._DENTHANG_NAM = value;
					this.SendPropertyChanged("DENTHANG_NAM");
					this.OnDENTHANG_NAMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCDANH", DbType="Char(50)")]
		public string CHUCDANH
		{
			get
			{
				return this._CHUCDANH;
			}
			set
			{
				if ((this._CHUCDANH != value))
				{
					this.OnCHUCDANHChanging(value);
					this.SendPropertyChanging();
					this._CHUCDANH = value;
					this.SendPropertyChanged("CHUCDANH");
					this.OnCHUCDANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUCVU", DbType="Char(50)")]
		public string CHUCVU
		{
			get
			{
				return this._CHUCVU;
			}
			set
			{
				if ((this._CHUCVU != value))
				{
					this.OnCHUCVUChanging(value);
					this.SendPropertyChanging();
					this._CHUCVU = value;
					this.SendPropertyChanged("CHUCVU");
					this.OnCHUCVUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGKHOA_QUATRINHCONGTAC", Storage="_PHONGKHOA", ThisKey="MAPHG", OtherKey="MAPHG", IsForeignKey=true)]
		public PHONGKHOA PHONGKHOA
		{
			get
			{
				return this._PHONGKHOA.Entity;
			}
			set
			{
				PHONGKHOA previousValue = this._PHONGKHOA.Entity;
				if (((previousValue != value) 
							|| (this._PHONGKHOA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONGKHOA.Entity = null;
						previousValue.QUATRINHCONGTACs.Remove(this);
					}
					this._PHONGKHOA.Entity = value;
					if ((value != null))
					{
						value.QUATRINHCONGTACs.Add(this);
						this._MAPHG = value.MAPHG;
					}
					else
					{
						this._MAPHG = default(string);
					}
					this.SendPropertyChanged("PHONGKHOA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_QUATRINHCONGTAC", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.QUATRINHCONGTACs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.QUATRINHCONGTACs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUYETDINH")]
	public partial class QUYETDINH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MAQD;
		
		private string _MAPHG;
		
		private string _MANV;
		
		private string _LOAIQD;
		
		private string _TENQD;
		
		private System.Nullable<System.DateTime> _NGAYRAQD;
		
		private EntityRef<PHONGKHOA> _PHONGKHOA;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMAQDChanging(string value);
    partial void OnMAQDChanged();
    partial void OnMAPHGChanging(string value);
    partial void OnMAPHGChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnLOAIQDChanging(string value);
    partial void OnLOAIQDChanged();
    partial void OnTENQDChanging(string value);
    partial void OnTENQDChanged();
    partial void OnNGAYRAQDChanging(System.Nullable<System.DateTime> value);
    partial void OnNGAYRAQDChanged();
    #endregion
		
		public QUYETDINH()
		{
			this._PHONGKHOA = default(EntityRef<PHONGKHOA>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAQD", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MAQD
		{
			get
			{
				return this._MAQD;
			}
			set
			{
				if ((this._MAQD != value))
				{
					this.OnMAQDChanging(value);
					this.SendPropertyChanging();
					this._MAQD = value;
					this.SendPropertyChanged("MAQD");
					this.OnMAQDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHG", DbType="VarChar(4)")]
		public string MAPHG
		{
			get
			{
				return this._MAPHG;
			}
			set
			{
				if ((this._MAPHG != value))
				{
					if (this._PHONGKHOA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMAPHGChanging(value);
					this.SendPropertyChanging();
					this._MAPHG = value;
					this.SendPropertyChanged("MAPHG");
					this.OnMAPHGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(4)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAIQD", DbType="Char(20)")]
		public string LOAIQD
		{
			get
			{
				return this._LOAIQD;
			}
			set
			{
				if ((this._LOAIQD != value))
				{
					this.OnLOAIQDChanging(value);
					this.SendPropertyChanging();
					this._LOAIQD = value;
					this.SendPropertyChanged("LOAIQD");
					this.OnLOAIQDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENQD", DbType="Char(50)")]
		public string TENQD
		{
			get
			{
				return this._TENQD;
			}
			set
			{
				if ((this._TENQD != value))
				{
					this.OnTENQDChanging(value);
					this.SendPropertyChanging();
					this._TENQD = value;
					this.SendPropertyChanged("TENQD");
					this.OnTENQDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYRAQD", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NGAYRAQD
		{
			get
			{
				return this._NGAYRAQD;
			}
			set
			{
				if ((this._NGAYRAQD != value))
				{
					this.OnNGAYRAQDChanging(value);
					this.SendPropertyChanging();
					this._NGAYRAQD = value;
					this.SendPropertyChanged("NGAYRAQD");
					this.OnNGAYRAQDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONGKHOA_QUYETDINH", Storage="_PHONGKHOA", ThisKey="MAPHG", OtherKey="MAPHG", IsForeignKey=true)]
		public PHONGKHOA PHONGKHOA
		{
			get
			{
				return this._PHONGKHOA.Entity;
			}
			set
			{
				PHONGKHOA previousValue = this._PHONGKHOA.Entity;
				if (((previousValue != value) 
							|| (this._PHONGKHOA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONGKHOA.Entity = null;
						previousValue.QUYETDINHs.Remove(this);
					}
					this._PHONGKHOA.Entity = value;
					if ((value != null))
					{
						value.QUYETDINHs.Add(this);
						this._MAPHG = value.MAPHG;
					}
					else
					{
						this._MAPHG = default(string);
					}
					this.SendPropertyChanged("PHONGKHOA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_QUYETDINH", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.QUYETDINHs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.QUYETDINHs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TENDANGNHAP;
		
		private string _MANV;
		
		private string _MATKHAU;
		
		private System.Nullable<bool> _QUYENTRUYCAP;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTENDANGNHAPChanging(string value);
    partial void OnTENDANGNHAPChanged();
    partial void OnMANVChanging(string value);
    partial void OnMANVChanged();
    partial void OnMATKHAUChanging(string value);
    partial void OnMATKHAUChanged();
    partial void OnQUYENTRUYCAPChanging(System.Nullable<bool> value);
    partial void OnQUYENTRUYCAPChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENDANGNHAP", DbType="Char(40) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TENDANGNHAP
		{
			get
			{
				return this._TENDANGNHAP;
			}
			set
			{
				if ((this._TENDANGNHAP != value))
				{
					this.OnTENDANGNHAPChanging(value);
					this.SendPropertyChanging();
					this._TENDANGNHAP = value;
					this.SendPropertyChanged("TENDANGNHAP");
					this.OnTENDANGNHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANV", DbType="VarChar(4)")]
		public string MANV
		{
			get
			{
				return this._MANV;
			}
			set
			{
				if ((this._MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANVChanging(value);
					this.SendPropertyChanging();
					this._MANV = value;
					this.SendPropertyChanged("MANV");
					this.OnMANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATKHAU", DbType="Char(40)")]
		public string MATKHAU
		{
			get
			{
				return this._MATKHAU;
			}
			set
			{
				if ((this._MATKHAU != value))
				{
					this.OnMATKHAUChanging(value);
					this.SendPropertyChanging();
					this._MATKHAU = value;
					this.SendPropertyChanged("MATKHAU");
					this.OnMATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUYENTRUYCAP", DbType="Bit")]
		public System.Nullable<bool> QUYENTRUYCAP
		{
			get
			{
				return this._QUYENTRUYCAP;
			}
			set
			{
				if ((this._QUYENTRUYCAP != value))
				{
					this.OnQUYENTRUYCAPChanging(value);
					this.SendPropertyChanging();
					this._QUYENTRUYCAP = value;
					this.SendPropertyChanged("QUYENTRUYCAP");
					this.OnQUYENTRUYCAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_TAIKHOAN", Storage="_NHANVIEN", ThisKey="MANV", OtherKey="MANV", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.TAIKHOANs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.TAIKHOANs.Add(this);
						this._MANV = value.MANV;
					}
					else
					{
						this._MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THANNHAN")]
	public partial class THANNHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MATN;
		
		private string _HOTENTN;
		
		private System.Nullable<System.DateTime> _NAMSINH;
		
		private string _QUANHE;
		
		private string _NGHENGHIEP;
		
		private string _DVCONGTAC;
		
		private EntitySet<COTN> _COTNs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMATNChanging(string value);
    partial void OnMATNChanged();
    partial void OnHOTENTNChanging(string value);
    partial void OnHOTENTNChanged();
    partial void OnNAMSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnNAMSINHChanged();
    partial void OnQUANHEChanging(string value);
    partial void OnQUANHEChanged();
    partial void OnNGHENGHIEPChanging(string value);
    partial void OnNGHENGHIEPChanged();
    partial void OnDVCONGTACChanging(string value);
    partial void OnDVCONGTACChanged();
    #endregion
		
		public THANNHAN()
		{
			this._COTNs = new EntitySet<COTN>(new Action<COTN>(this.attach_COTNs), new Action<COTN>(this.detach_COTNs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MATN", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MATN
		{
			get
			{
				return this._MATN;
			}
			set
			{
				if ((this._MATN != value))
				{
					this.OnMATNChanging(value);
					this.SendPropertyChanging();
					this._MATN = value;
					this.SendPropertyChanged("MATN");
					this.OnMATNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTENTN", DbType="Char(50)")]
		public string HOTENTN
		{
			get
			{
				return this._HOTENTN;
			}
			set
			{
				if ((this._HOTENTN != value))
				{
					this.OnHOTENTNChanging(value);
					this.SendPropertyChanging();
					this._HOTENTN = value;
					this.SendPropertyChanged("HOTENTN");
					this.OnHOTENTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAMSINH", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NAMSINH
		{
			get
			{
				return this._NAMSINH;
			}
			set
			{
				if ((this._NAMSINH != value))
				{
					this.OnNAMSINHChanging(value);
					this.SendPropertyChanging();
					this._NAMSINH = value;
					this.SendPropertyChanged("NAMSINH");
					this.OnNAMSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QUANHE", DbType="Char(20)")]
		public string QUANHE
		{
			get
			{
				return this._QUANHE;
			}
			set
			{
				if ((this._QUANHE != value))
				{
					this.OnQUANHEChanging(value);
					this.SendPropertyChanging();
					this._QUANHE = value;
					this.SendPropertyChanged("QUANHE");
					this.OnQUANHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGHENGHIEP", DbType="Char(50)")]
		public string NGHENGHIEP
		{
			get
			{
				return this._NGHENGHIEP;
			}
			set
			{
				if ((this._NGHENGHIEP != value))
				{
					this.OnNGHENGHIEPChanging(value);
					this.SendPropertyChanging();
					this._NGHENGHIEP = value;
					this.SendPropertyChanged("NGHENGHIEP");
					this.OnNGHENGHIEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DVCONGTAC", DbType="Char(50)")]
		public string DVCONGTAC
		{
			get
			{
				return this._DVCONGTAC;
			}
			set
			{
				if ((this._DVCONGTAC != value))
				{
					this.OnDVCONGTACChanging(value);
					this.SendPropertyChanging();
					this._DVCONGTAC = value;
					this.SendPropertyChanged("DVCONGTAC");
					this.OnDVCONGTACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANNHAN_COTN", Storage="_COTNs", ThisKey="MATN", OtherKey="MATN")]
		public EntitySet<COTN> COTNs
		{
			get
			{
				return this._COTNs;
			}
			set
			{
				this._COTNs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_COTNs(COTN entity)
		{
			this.SendPropertyChanging();
			entity.THANNHAN = this;
		}
		
		private void detach_COTNs(COTN entity)
		{
			this.SendPropertyChanging();
			entity.THANNHAN = null;
		}
	}
}
#pragma warning restore 1591
